# If having any issues with the docker network:
# https://github.com/docker/for-win/issues/2194

# how to run a container after the ones from which it depends on:
# https://medium.com/better-programming/a-look-at-docker-composes-bootup-sequence-1f597049cc65
services:
  interceptor:
   container_name: interceptor
   build: 
    context: .
    dockerfile: Docker/interceptor/Dockerfile
   
   image: interceptor:latest
   entrypoint: ["python3", "Interceptor.py", "--mode", "container", "--compose", "docker-compose.yml"]
   
   # binding host docker sock to this container to send http requests to host's docker engine.
   # this practise could offer to an attacker the chance to penetrate into the host system:
   # https://stackoverflow.com/questions/40844197/what-is-the-docker-security-risk-of-var-run-docker-sock 
   #volumes:
   #- "/var/run/docker.sock:/var/run/docker.sock"
   
   # docker-compose.yml will be employed to make the other containers name known to this one.
   volumes:
   - "./docker-compose.yml:/WAPT-Dataset-Collector/code/docker-compose.yml"
   ports:
    - "8888:8888"
   networks:
     - penetration_net
   # this enforces docker to build this container after that the others on which it depends.
   depends_on:
    - benchmark
     
  benchmark:
    container_name: benchmark
    build: 
      context: .
      dockerfile: Docker/wavsep/Dockerfile
   
    image: wavsep:latest
    restart: always
    ports:
     - "8080:8080"
    networks:
     - penetration_net
        
  
networks:
  penetration_net:
    name: 'penetration_net'
    driver: bridge
    
