version: '2'
services:
  wavsep:
    container_name: wavsep
    image: wavsep:latest
    restart: always
    ports:
     - "8080:8080"
    networks:
      penetration_net:
        ipv4_address: 10.5.0.5

  interceptor:
    container_name: interceptor
    image: interceptor:latest
    entrypoint: ["python3", "Interceptor.py", "-ph", "10.5.0.6", "-pp", "8888", "-bh", "10.5.0.5", "-bp", "8080"]    
    ports:
     - "8888:8888"
    networks:
      penetration_net:
        ipv4_address: 10.5.0.6

networks:
  penetration_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
